apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 415718916760.dkr.ecr.us-east-1.amazonaws.com/demo-frontend
  newName: 415718916760.dkr.ecr.us-east-1.amazonaws.com/demo-frontend
  newTag: 1347cf55
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
